// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-C7WkcvYW5HwA7Jr6BSiBEsScsmrWh8',
    appId: '1:414977193950:web:20434b6ad263f96874cf4f',
    messagingSenderId: '414977193950',
    projectId: 'sales-bab47',
    authDomain: 'sales-bab47.firebaseapp.com',
    storageBucket: 'sales-bab47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCuPn0NYHhaDFeXvoMcEbU4nveukmQ-0',
    appId: '1:414977193950:android:7d50180dbadede6974cf4f',
    messagingSenderId: '414977193950',
    projectId: 'sales-bab47',
    storageBucket: 'sales-bab47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfvCd7h8umLVHJFuprHi3v-AFDVEFWr8o',
    appId: '1:414977193950:ios:a5c7e9f32bb2c45574cf4f',
    messagingSenderId: '414977193950',
    projectId: 'sales-bab47',
    storageBucket: 'sales-bab47.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
